language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - sh -c "phpize && ./configure --with-pthread && make && make install"
  - sh -c "echo extension=blast.so | tee -a /home/vagrant/.phpenv/versions/*/etc/php.ini"
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - php examples/die_violently.php
